### ISSUE TITLE
error

### ISSUE THREAD

**Issue by samukas81** [warwick320/5G-deauther-with-OLED-SSD1306#1]
Hello, I'm trying to compile but I get this error, can you help, thank you.
![Erro](https://github.com/user-attachments/assets/07a7e5c8-7192-497a-bacc-6d9fbbb603bb)

**Comment by 7JKD** [comment]
Brother, the source file and header file attached after you have not been added.

**Comment by samukas81** [comment]
and where do I download these files?

**Comment by samukas81** [comment]
I can't compile, could you pass your script? Thanks.
