### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by samukas81** [warwick320/5G-deauther-with-OLED-SSD1306#5]
How did you manage to compile if the sketch has a problem?

**Comment by WXLN** [comment]
It's because of the library file issue with OLED, as it supports a wide range, you need to modify it to a working mode suitable for BW16

**Comment by samukas81** [comment]
Hello, and what would be the working mode for OLED 1306?

**Comment by WXLN** [comment]
即便是修复好了攻击也没有效果，聪明的已经自己构建代码了。[
![IMG_20241110_123812](https://github.com/user-attachments/assets/e0b0e7c5-7333-4285-aacd-3ef4db33b8c9)
](url)

**Comment by samukas81** [comment]
Can you pass the fixed sketch?

**Comment by samukas81** [comment]
share the code

**Comment by WXLN** [comment]
> 分享代码

No, this is a closed source firmware from another author
