### ISSUE TITLE
Error Compile

### ISSUE THREAD

**Issue by sulintang** [warwick320/5G-deauther-with-OLED-SSD1306#6]
In file included from C:\Users\komputer\Documents\Arduino\libraries\Adafruit-GFX-Library-master/Adafruit_GFX.h:13:0,
                 from E:\deauther\5ghz\5G-deauther-with-OLED-SSD1306-BETA\RTL8720dn-Deauther-V1\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:14:
C:\Users\komputer\Documents\Arduino\libraries\Adafruit_BusIO-master/Adafruit_SPIDevice.h:95:41: error: 'SPI_MODE0' was not declared in this scope
                      uint8_t dataMode = SPI_MODE0, SPIClass *theSPI = &SPI);
                                         ^~~~~~~~~
C:\Users\komputer\Documents\Arduino\libraries\Adafruit_BusIO-master/Adafruit_SPIDevice.h:104:41: error: 'SPI_MODE0' was not declared in this scope
                      uint8_t dataMode = SPI_MODE0);
                                         ^~~~~~~~~
E:\deauther\5ghz\5G-deauther-with-OLED-SSD1306-BETA\RTL8720dn-Deauther-V1\RTL8720dn-Deauther\RTL8720dn-Deauther.ino: In function 'void setup()':
RTL8720dn-Deauther:104:8: error: 'class WiFiClass' has no member named 'apbegin'; did you mean 'begin'?
   WiFi.apbegin(ssid, pass, (char *) String(current_channel).c_str());
        ^~~~~~~
E:\deauther\5ghz\5G-deauther-with-OLED-SSD1306-BETA\RTL8720dn-Deauther-V1\RTL8720dn-Deauther\RTL8720dn-Deauther.ino: In function 'void loop()':
RTL8720dn-Deauther:149:14: error: 'class WiFiClass' has no member named 'apbegin'; did you mean 'begin'?
         WiFi.apbegin(ssid, pass, (char *) String(current_channel).c_str());
              ^~~~~~~
E:\deauther\5ghz\5G-deauther-with-OLED-SSD1306-BETA\RTL8720dn-Deauther-V1\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:163:13: warning: unused variable 'deauth_reason2' [-Wunused-variable]
         int deauth_reason2 = 14;
             ^~~~~~~~~~~~~~
RTL8720dn-Deauther:189:19: error: 'class WiFiClass' has no member named 'apbegin'; did you mean 'begin'?
              WiFi.apbegin(ssid, pass, (char *) String(current_channel).c_str());
                   ^~~~~~~
E:\deauther\5ghz\5G-deauther-with-OLED-SSD1306-BETA\RTL8720dn-Deauther-V1\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:228:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (scrollIndex < scan_results.size() - 1) {
                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
E:\deauther\5ghz\5G-deauther-with-OLED-SSD1306-BETA\RTL8720dn-Deauther-V1\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:229:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               if (scrollIndex == scan_results.size() - 1 ){
                   ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
E:\deauther\5ghz\5G-deauther-with-OLED-SSD1306-BETA\RTL8720dn-Deauther-V1\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:265:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (scrollIndex <= scan_results.size()) {
                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
E:\deauther\5ghz\5G-deauther-with-OLED-SSD1306-BETA\RTL8720dn-Deauther-V1\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:321:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (scrollIndex <= scan_results.size()){
                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
E:\deauther\5ghz\5G-deauther-with-OLED-SSD1306-BETA\RTL8720dn-Deauther-V1\RTL8720dn-Deauther\RTL8720dn-Deauther.ino: In function 'String getMenuName(int)':
E:\deauther\5ghz\5G-deauther-with-OLED-SSD1306-BETA\RTL8720dn-Deauther-V1\RTL8720dn-Deauther\RTL8720dn-Deauther.ino:392:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
exit status 1
'class WiFiClass' has no member named 'apbegin'; did you mean 'begin'?

**Comment by samukas81** [comment]
bad sketch

**Comment by sulintang** [comment]
you can help me please?

**Comment by samukas81** [comment]
I'm also looking for help, but I think the developer doesn't care about his project.

**Comment by warwick320** [comment]
check readme

**Comment by warwick320** [comment]
or send a DM on Discord.
My discord id is sihoo.320

**Comment by samukas81** [comment]
no work
